@host = http://localhost:4400

###

GET {{host}}/hello

###
POST {{host}}/greet
Content-Type: application/json

{
    "name": "Bob"
}

###
POST {{host}}/greet
Content-Type: application/json

{
    "name": "Alice"
}

###
POST {{host}}/greet
Content-Type: application/json

{
    "name": "Gergő"
}


